# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: **Edgar Roberto Valarezo Vargas**  <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema:
> 1. Sesiones de doblaje <br>
>2. Organizar los horarios de partidos de La Liga<br>
>3. Combinar cifras y operaciones

Descripción del problema:(copiar enunciado)

....

(*) La respuesta es obligatoria





                                        

**PROBLEMA 1: Sesiones de Doblaje**

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran toda la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.


Los datos son:

Número de actores: 10

Número de tomas: 30

Actores/Tomas: https://bit.ly/36D8IuK
* 1 indica que el actor participa en la toma
* 0 en caso contrario



- (*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



- ¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




**Respuesta**

Tomando en cuenta que las principales restricciones del problema son:

1. No se puede grabar más de 6 tomas por día, lo que limita la cantidad de trabajo diario independientemente de cuántos actores estén disponibles.

2. La programación de las tomas que se tiene en el archivo Excel toma en cuenta qué actores necesitan estar presentes juntos en el estudio para una toma específica.

Por ello, **sin tener en cuenta las restricciones**, básicamente se tienen infinitas respuestas, ya que las tomas podrían realizarse por múltiples vías de solución al aplicar fuerza bruta. Con esto se deben generar todas las combinaciones de tomas para cada día, y seleccionar la combinación de días que minimice el costo total.

Ahora, si **tomamos en cuenta las restricciones** se tiene que realizar una combinación de las tomas por día, con respecto a los actores requeridos, siempre y cuando no superen las 6 tomas diarias.

**Modelo para el espacio de soluciones<br>**
- (*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


Respuesta

La estructura de datos que mejor se adapta al problema es un grafo, donde los nodos representan a los actores y a las tomas. Este modelo facilita la comprensión del problema, así como visualizar las relaciones entre actores y sus tomas.

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

Respuesta

- La función objetivo es el reducir al máximo posible el gasto final por los servicios de los actores que asisten a grabar mediante la minimización del número total de días necesarios para completar todas las tomas.

- Se considera que este es un problema de minimización, ya que el objetivo es reducir al mínimo el número de días de grabación y por consecuencia, el costo total.

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

In [ ]:
import numpy as np

matriz_actor_x_toma = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
])

In [ ]:
from itertools import combinations
import pandas as pd

def optimizar_dias(matriz_actor_x_toma, max_tomas_por_dia):

    actores_en_toma = {}

    # Generar un array con formato donde se verifique facilmente los actores por toma
    for i, toma in enumerate(matriz_actor_x_toma):
        actores = []
        for j, asistencia in enumerate(toma):
            if asistencia == 1:
                actores.append(j + 1)
        actores_en_toma[i + 1] = actores

    # print(actores_en_toma)

    dias = []
    tomas_pendientes = set(range(1,31))

    # Recorrer cada toma planificada, con los actores necesarios para cada una de ellas
    # En cada recorrido se evaluan las tomas no consideradas en el recorrido anterior.

    while tomas_pendientes:
        mejor_combinacion = []
        max_actores_seleccionados = 0

        # Recorrido para combinar hasta un máximo de 6 tomas por día
        for i in range(1, max_tomas_por_dia + 1):

            # Recorrido para combinar las tomas (tomadas desde su ID)
            for combinacion in combinations(tomas_pendientes, i):
                actores_combinados = set()

                # Para cada combinación posible, se genera un Set (evitando duplicados) de actores requeridos en cada día
                # Por ejemplo, la Toma 1 (actores 1, 2, 3, 4 y 5) combinada con la toma 16 (actores 4 y 10) resulta un arreglo [1, 2, 3, 4, 5, 10]
                # O combinando la Toma 1 (actores 1, 2, 3, 4 y 5), toma 4 (actores 1, 2, 7 y 8) y la toma 11 (actores 1, 2, 3, 5 y 8) resulta el arreglo [1, 2, 3,4, 5, 7, 8]
                # Con esto se actualiza el Set de actores combinados cada vez

                for toma in combinacion:
                    actores_combinados.update(actores_en_toma[toma])

                # Asegurar que el numero de actores seleccionados no supere el numero de los actores combinados
                if len(actores_combinados) > max_actores_seleccionados:

                    # Con ello encuentro que la mejor combinación hasta el momento es la actual
                    mejor_combinacion = combinacion

                    # Aumentar el maximo de actores seleccionados cada vez
                    max_actores_seleccionados = len(actores_combinados)

        dias.append(mejor_combinacion)

        # Eliminar de las tomas pendientes totales las tomas seleccionadas hasta el momento
        tomas_pendientes -= set(mejor_combinacion)

    return dias

In [ ]:
# Restricciones
max_tomas_por_dia = 6

resultado = optimizar_dias(matriz_actor_x_toma, max_tomas_por_dia)
print('Número de días calculados:', len(resultado))
print(pd.DataFrame(resultado).fillna('-'))

Número de días calculados: 12
     0     1     2     3
0    1   4.0  10.0  16.0
1    3  21.0  25.0  26.0
2   11  12.0  15.0     -
3    2   5.0   8.0     -
4    6  14.0     -     -
5    7  18.0     -     -
6   22  29.0     -     -
7    9  13.0  24.0     -
8   20     -     -     -
9   17  27.0     -     -
10  19  28.0     -     -
11  23  30.0     -     -


Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

Se tiene una complejidad exponencial, ya que se utilizan multiples bucles dentro de la función utilizada.

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

In [ ]:
# Optimización de los días planificados

def optimizar_dias_planificados(dias, max_tomas_por_dia):
    dias_optimizados = []
    dias_cp = dias.copy()

    # Recorrer cada día de la respuesta anterior para optimizarlo
    while dias_cp:
        dia_actual = set(dias_cp.pop(0))
        combinado = False

        # Unir los días para cumplir el máximo de 6 tomas al día
        for i, dia in enumerate(dias_cp):
            if len(dia_actual | set(dia)) <= max_tomas_por_dia:
                dias_cp[i] = list(dia_actual | set(dia))
                combinado = True
                break
        if not combinado:
            dias_optimizados.append(list(dia_actual))
    return dias_optimizados


dias_optimizados = optimizar_dias_planificados(dias, max_tomas_por_dia)
print('Número de días luego de optimización:', len(dias_optimizados))
print(pd.DataFrame(dias_optimizados).fillna('-'))


Número de días luego de optimización: 5
    0   1   2   3   4   5
0   2   5   8  11  12  15
1   1   4   6  10  14  16
2   3   7  18  21  25  26
3   9  13  20  22  24  29
4  17  19  23  27  28  30


(*)Calcula la complejidad del algoritmo

Respuesta

La complejidad sigue siendo de Orden exponencial, ya que sigue subordinada al Orden de las operaciones utilizadas en el punto anterior.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [ ]:
datos_aleatorios = np.random.randint(2, size=(30,5))

print(datos_aleatorios)

[[1 1 1 0 0]
 [0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 1 0 1]
 [0 1 1 0 1]
 [1 1 1 1 0]
 [0 1 1 0 1]
 [1 1 1 1 0]
 [0 1 1 1 0]
 [1 0 0 0 1]
 [1 1 0 0 1]
 [0 1 1 1 0]
 [1 0 0 1 0]
 [1 0 0 0 0]
 [0 1 1 0 0]
 [1 1 0 1 1]
 [0 1 1 0 1]
 [1 0 0 0 0]
 [1 0 0 1 0]
 [1 1 0 1 0]
 [1 0 0 0 0]
 [0 0 1 1 0]
 [1 0 0 1 0]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [0 1 0 1 1]
 [1 0 1 0 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 0]]


Aplica el algoritmo al juego de datos generado

Respuesta

In [ ]:
maximo_tomas = 5
resultado_test = optimizar_dias(datos_aleatorios, maximo_tomas)
print('Número de días calculados:', len(resultado_test))
print(pd.DataFrame(resultado_test).fillna('-'))

resultado_test2 = optimizar_dias_planificados(resultado_test, maximo_tomas)
print('Número de días luego de optimización:', len(resultado_test2))
print(pd.DataFrame(resultado_test2).fillna('-'))

Número de días calculados: 15
     0     1     2
0    1  16.0     -
1    2   6.0     -
2    3  26.0     -
3    4   8.0     -
4    5  13.0     -
5    7  19.0     -
6    9  10.0     -
7   11  12.0     -
8   17  20.0     -
9   14  22.0  28.0
10  15  23.0  29.0
11  25  30.0     -
12  27     -     -
13  18  24.0     -
14  21     -     -
Número de días luego de optimización: 7
    0   1     2     3     4
0   5  19  13.0   7.0     -
1   9  10  11.0  12.0     -
2  14  17  20.0  22.0  28.0
3  15  23  25.0  29.0  30.0
4   1   2   6.0  16.0  27.0
5  24  18     -     -     -
6   3   4   8.0  21.0  26.0


Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta